services:
  - type: web
    name: foodle-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "{{.SERVICE_NAME}}.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True

databases:
  - name: foodle-db
    databaseName: foodle
    user: foodle_user
