# Generated by Django 5.1.7 on 2025-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("private", "Privé - Sur invitation uniquement"),
                    ("public", "Public - Ouvert à tous"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
