# Generated by Django 5.1.7 on 2025-03-29 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="groups.group",
            ),
            preserve_default=False,
        ),
    ]
